version: 2

registries:
  npm-bit:
    type: npm-registry
    url: https://node-registry.bit.cloud
    token: ${{secrets.DEPENDABOT_TOKEN}}
    replace-base: true

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@itaysso/*"